name: My Pipeline

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          pip install --only-binary :all: uv
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run docker
        run: |
          make start
      - name: Run test coverage
        run: |
          make test-coverage
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=yannay000_qa-auto-engineer-python-project-314
            -Dsonar.organization=yannay000
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
            -Dsonar.exclusions=config.py